# **Import Libraries**

In [ ]:
# Numpy -> for numerical operations (mean, arrays, math)
import numpy as np

# Pandas -> for data handling (tables like excel)
import pandas as pd

# Matplotlib -> for basic graphs
import matplotlib.pyplot as plt

#  seaborn -> for advanced & better-looking visualizations
import seaborn as sns

# **Load Data**

In [ ]:
data_csv = pd.read_csv("data/coffee_sales.csv")
data_csv

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,01/03/2024,01/03/2024 10:15:51,10,card,ANON-0000-0000-0001,R38.70,Latte,Morning,Fri,Mar,5,3
1,01/03/2024,01/03/2024 12:19:23,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,01/03/2024,01/03/2024 12:20:18,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,01/03/2024,01/03/2024 13:46:33,13,card,ANON-0000-0000-0003,R28.90,Americano,Afternoon,Fri,Mar,5,3
4,01/03/2024,01/03/2024 13:48:15,13,card,ANON-0000-0000-0004,R38.70,Latte,Afternoon,Fri,Mar,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3631,23/03/2025,23/03/2025 10:34:55,10,card,ANON-0000-0000-1158,R35.76,Cappuccino,Morning,Sun,Mar,7,3
3632,23/03/2025,23/03/2025 14:43:37,14,card,ANON-0000-0000-1315,R35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,23/03/2025,23/03/2025 14:44:17,14,card,ANON-0000-0000-1315,R35.76,Cocoa,Afternoon,Sun,Mar,7,3
3634,23/03/2025,23/03/2025 15:47:29,15,card,ANON-0000-0000-1316,R25.96,Americano,Afternoon,Sun,Mar,7,3
3635,23/03/2025,23/03/2025 18:11:39,18,card,ANON-0000-0000-1275,R35.76,Latte,Night,Sun,Mar,7,3

In [ ]:
# First 5 rows
data_csv.head()

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,01/03/2024,01/03/2024 10:15:51,10,card,ANON-0000-0000-0001,R38.70,Latte,Morning,Fri,Mar,5,3
1,01/03/2024,01/03/2024 12:19:23,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,01/03/2024,01/03/2024 12:20:18,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,01/03/2024,01/03/2024 13:46:33,13,card,ANON-0000-0000-0003,R28.90,Americano,Afternoon,Fri,Mar,5,3
4,01/03/2024,01/03/2024 13:48:15,13,card,ANON-0000-0000-0004,R38.70,Latte,Afternoon,Fri,Mar,5,3

In [ ]:
# Shape (rows, columns)
print("shape:", data_csv.shape)

shape: (3636, 12)

In [ ]:
# Columns name
print("columns:", data_csv.columns)

columns: Index(['date', 'datetime', 'hour_of_day', 'cash_type', 'card', 'money',
       'coffee_name', 'Time_of_Day', 'Weekday', 'Month_name', 'Weekdaysort',
       'Monthsort'],
      dtype='str')

# Basic Data Understanding

In [ ]:
# Info about the dataset
data_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   str
 1   datetime     3636 non-null   str
 2   hour_of_day  3636 non-null   int64
 3   cash_type    3636 non-null   str
 4   card         3547 non-null   str
 5   money        3636 non-null   str
 6   coffee_name  3636 non-null   str
 7   Time_of_Day  3636 non-null   str
 8   Weekday      3636 non-null   str
 9   Month_name   3636 non-null   str
 10  Weekdaysort  3636 non-null   int64
 11  Monthsort    3636 non-null   int64
dtypes: int64(3), str(9)
memory usage: 341.0 KB

In [ ]:
#  Statistical summary

data_csv.describe()

       hour_of_day  Weekdaysort    Monthsort
count  3636.000000  3636.000000  3636.000000
mean     14.166942     3.847910     6.394664
std       4.227755     1.975983     3.480686
min       6.000000     1.000000     1.000000
25%      10.000000     2.000000     3.000000
50%      14.000000     4.000000     6.000000
75%      18.000000     6.000000    10.000000
max      22.000000     7.000000    12.000000

In [ ]:
#  Data types
print(data_csv.dtypes)

date             str
datetime         str
hour_of_day    int64
cash_type        str
card             str
money            str
coffee_name      str
Time_of_Day      str
Weekday          str
Month_name       str
Weekdaysort    int64
Monthsort      int64
dtype: object

# Data Cleaning

In [ ]:
#  Checking missing values

print(data_csv.isnull().sum())

date            0
datetime        0
hour_of_day     0
cash_type       0
card           89
money           0
coffee_name     0
Time_of_Day     0
Weekday         0
Month_name      0
Weekdaysort     0
Monthsort       0
dtype: int64

In [ ]:
#  Handle missing values (card column)

data_csv["card"] = data_csv["card"].fillna("No card")

data_csv["card"]

0       ANON-0000-0000-0001
1       ANON-0000-0000-0002
2       ANON-0000-0000-0002
3       ANON-0000-0000-0003
4       ANON-0000-0000-0004
               ...
3631    ANON-0000-0000-1158
3632    ANON-0000-0000-1315
3633    ANON-0000-0000-1315
3634    ANON-0000-0000-1316
3635    ANON-0000-0000-1275
Name: card, Length: 3636, dtype: str

In [ ]:
#  duplicate
data_csv["card"].duplicated().sum()

np.int64(2319)

In [ ]:
data_csv["card"].nunique()

1317

In [ ]:
# Remove duplicates

print(data_csv.drop_duplicates(inplace=True))

None

In [ ]:
# Fix column names (lowercase + no spaces)

data_csv.columns = data_csv.columns.str.lower().str.replace(" ", "_")

data_csv.columns

Index(['date', 'datetime', 'hour_of_day', 'cash_type', 'card', 'money',
       'coffee_name', 'time_of_day', 'weekday', 'month_name', 'weekdaysort',
       'monthsort'],
      dtype='str')

In [ ]:
#  Convert date column

data_csv["date"] = pd.to_datetime(data_csv["date"], dayfirst=True)

data_csv["datetime"] = pd.to_datetime(data_csv["datetime"], dayfirst=True)

data_csv["date"]
data_csv["datetime"]

0      2024-03-01 10:15:51
1      2024-03-01 12:19:23
2      2024-03-01 12:20:18
3      2024-03-01 13:46:33
4      2024-03-01 13:48:15
               ...
3631   2025-03-23 10:34:55
3632   2025-03-23 14:43:37
3633   2025-03-23 14:44:17
3634   2025-03-23 15:47:29
3635   2025-03-23 18:11:39
Name: datetime, Length: 3636, dtype: datetime64[us]

In [ ]:
data_csv['money'] = data_csv['money'].str.replace('R','').astype(float)

In [ ]:
data_csv

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,time_of_day,weekday,month_name,weekdaysort,monthsort
0,2024-03-01,2024-03-01 10:15:51,10,card,ANON-0000-0000-0001,38.70,Latte,Morning,Fri,Mar,5,3
1,2024-03-01,2024-03-01 12:19:23,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,2024-03-01,2024-03-01 12:20:18,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,2024-03-01,2024-03-01 13:46:33,13,card,ANON-0000-0000-0003,28.90,Americano,Afternoon,Fri,Mar,5,3
4,2024-03-01,2024-03-01 13:48:15,13,card,ANON-0000-0000-0004,38.70,Latte,Afternoon,Fri,Mar,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:55,10,card,ANON-0000-0000-1158,35.76,Cappuccino,Morning,Sun,Mar,7,3
3632,2025-03-23,2025-03-23 14:43:37,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,2025-03-23,2025-03-23 14:44:17,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3634,2025-03-23,2025-03-23 15:47:29,15,card,ANON-0000-0000-1316,25.96,Americano,Afternoon,Sun,Mar,7,3
3635,2025-03-23,2025-03-23 18:11:39,18,card,ANON-0000-0000-1275,35.76,Latte,Night,Sun,Mar,7,3

# Data Manipulation

In [ ]:
# Filtering afternoon sales only 

afternoon_sales = data_csv[data_csv["time_of_day"] == "Afternoon"]

afternoon_sales

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,time_of_day,weekday,month_name,weekdaysort,monthsort
1,2024-03-01,2024-03-01 12:19:23,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,2024-03-01,2024-03-01 12:20:18,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,2024-03-01,2024-03-01 13:46:33,13,card,ANON-0000-0000-0003,28.90,Americano,Afternoon,Fri,Mar,5,3
4,2024-03-01,2024-03-01 13:48:15,13,card,ANON-0000-0000-0004,38.70,Latte,Afternoon,Fri,Mar,5,3
5,2024-03-01,2024-03-01 15:39:48,15,card,ANON-0000-0000-0005,33.80,Americano with Milk,Afternoon,Fri,Mar,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3626,2025-03-22,2025-03-22 15:57:58,15,card,ANON-0000-0000-1302,21.06,Espresso,Afternoon,Sat,Mar,6,3
3627,2025-03-22,2025-03-22 16:27:00,16,card,ANON-0000-0000-1274,35.76,Latte,Afternoon,Sat,Mar,6,3
3632,2025-03-23,2025-03-23 14:43:37,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,2025-03-23,2025-03-23 14:44:17,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3634,2025-03-23,2025-03-23 15:47:29,15,card,ANON-0000-0000-1316,25.96,Americano,Afternoon,Sun,Mar,7,3

In [ ]:
morning_sales = data_csv[data_csv["time_of_day"] == "Morning" ]

morning_sales

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,time_of_day,weekday,month_name,weekdaysort,monthsort
0,2024-03-01,2024-03-01 10:15:51,10,card,ANON-0000-0000-0001,38.70,Latte,Morning,Fri,Mar,5,3
11,2024-03-02,2024-03-02 10:22:07,10,card,ANON-0000-0000-0010,28.90,Americano,Morning,Sat,Mar,6,3
12,2024-03-02,2024-03-02 10:30:36,10,cash,No card,40.00,Latte,Morning,Sat,Mar,6,3
13,2024-03-02,2024-03-02 10:41:41,10,card,ANON-0000-0000-0011,33.80,Americano with Milk,Morning,Sat,Mar,6,3
14,2024-03-02,2024-03-02 11:59:45,11,card,ANON-0000-0000-0012,33.80,Americano with Milk,Morning,Sat,Mar,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3619,2025-03-22,2025-03-22 10:30:09,10,card,ANON-0000-0000-1152,30.86,Americano with Milk,Morning,Sat,Mar,6,3
3620,2025-03-22,2025-03-22 11:14:06,11,card,ANON-0000-0000-1259,35.76,Hot Chocolate,Morning,Sat,Mar,6,3
3621,2025-03-22,2025-03-22 11:41:21,11,card,ANON-0000-0000-1279,35.76,Cocoa,Morning,Sat,Mar,6,3
3630,2025-03-23,2025-03-23 10:07:11,10,card,ANON-0000-0000-1196,35.76,Latte,Morning,Sun,Mar,7,3
3631,2025-03-23,2025-03-23 10:34:55,10,card,ANON-0000-0000-1158,35.76,Cappuccino,Morning,Sun,Mar,7,3

In [ ]:
night_sales = data_csv[data_csv["time_of_day"] == "Night"]

night_sales

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,time_of_day,weekday,month_name,weekdaysort,monthsort
7,2024-03-01,2024-03-01 18:39:04,18,card,ANON-0000-0000-0007,33.80,Americano with Milk,Night,Fri,Mar,5,3
8,2024-03-01,2024-03-01 19:22:02,19,card,ANON-0000-0000-0008,38.70,Cocoa,Night,Fri,Mar,5,3
9,2024-03-01,2024-03-01 19:23:16,19,card,ANON-0000-0000-0008,33.80,Americano with Milk,Night,Fri,Mar,5,3
10,2024-03-01,2024-03-01 19:29:17,19,card,ANON-0000-0000-0009,33.80,Americano with Milk,Night,Fri,Mar,5,3
17,2024-03-02,2024-03-02 17:34:55,17,card,ANON-0000-0000-0004,28.90,Americano,Night,Sat,Mar,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3616,2025-03-21,2025-03-21 18:52:13,18,card,ANON-0000-0000-0507,35.76,Latte,Night,Fri,Mar,5,3
3617,2025-03-21,2025-03-21 18:59:24,18,card,ANON-0000-0000-1170,25.96,Americano,Night,Fri,Mar,5,3
3628,2025-03-22,2025-03-22 17:53:36,17,card,ANON-0000-0000-1274,30.86,Americano with Milk,Night,Sat,Mar,6,3
3629,2025-03-22,2025-03-22 19:16:53,19,card,ANON-0000-0000-1314,30.86,Americano with Milk,Night,Sat,Mar,6,3
3635,2025-03-23,2025-03-23 18:11:39,18,card,ANON-0000-0000-1275,35.76,Latte,Night,Sun,Mar,7,3

In [ ]:
data_csv["time_of_day"].value_counts()

time_of_day
Afternoon    1231
Morning      1221
Night        1184
Name: count, dtype: int64

In [ ]:
#  groupby

data_csv.groupby("time_of_day").size()

time_of_day
Afternoon    1231
Morning      1221
Night        1184
dtype: int64

In [ ]:
# Percentage

data_csv["time_of_day"].value_counts(normalize=True) * 100

time_of_day
Afternoon    33.855886
Morning      33.580858
Night        32.563256
Name: proportion, dtype: float64

In [ ]:
# Round clean output:

data_csv["time_of_day"].value_counts(normalize=True).mul(100).round(2)

time_of_day
Afternoon    33.86
Morning      33.58
Night        32.56
Name: proportion, dtype: float64

In [ ]:

data_csv["time_of_day"].value_counts(normalize=True).mul(100).round(0).astype(int)

time_of_day
Afternoon    34
Morning      34
Night        33
Name: proportion, dtype: int64

In [ ]:
# Selecting columns

selected = data_csv[["coffee_name", "money"]]

selected

        coffee_name  money
0             Latte  38.70
1     Hot Chocolate  38.70
2     Hot Chocolate  38.70
3         Americano  28.90
4             Latte  38.70
...             ...    ...
3631     Cappuccino  35.76
3632          Cocoa  35.76
3633          Cocoa  35.76
3634      Americano  25.96
3635          Latte  35.76

[3636 rows x 2 columns]

In [ ]:
#  Create new column (high value order)

data_csv["high_sales"] = data_csv["money"].apply(lambda x: "yes" if x > 30 else "No")

data_csv["high_sales"]

0       yes
1       yes
2       yes
3        No
4       yes
       ...
3631    yes
3632    yes
3633    yes
3634     No
3635    yes
Name: high_sales, Length: 3636, dtype: str

In [ ]:
data_csv[["coffee_name", "money", "high_sales"]]

        coffee_name  money high_sales
0             Latte  38.70        yes
1     Hot Chocolate  38.70        yes
2     Hot Chocolate  38.70        yes
3         Americano  28.90         No
4             Latte  38.70        yes
...             ...    ...        ...
3631     Cappuccino  35.76        yes
3632          Cocoa  35.76        yes
3633          Cocoa  35.76        yes
3634      Americano  25.96         No
3635          Latte  35.76        yes

[3636 rows x 3 columns]

In [ ]:
# Map example

data_csv["payment"] = data_csv["cash_type"].map({"card" : 1, "cash": 0})

print(data_csv["payment"])
print(data_csv["cash_type"])

0       1
1       1
2       1
3       1
4       1
       ..
3631    1
3632    1
3633    1
3634    1
3635    1
Name: payment, Length: 3636, dtype: int64
0       card
1       card
2       card
3       card
4       card
        ...
3631    card
3632    card
3633    card
3634    card
3635    card
Name: cash_type, Length: 3636, dtype: str

In [ ]:
data_sorted = data_csv.sort_values(by="money", ascending=False)

data_sorted

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,time_of_day,weekday,month_name,weekdaysort,monthsort,high_sales,payment
46,2024-03-07,2024-03-07 10:08:59,10,cash,No card,40.00,Latte,Morning,Thu,Mar,4,3,yes,0
232,2024-04-05,2024-04-05 15:30:50,15,cash,No card,40.00,Latte,Afternoon,Fri,Apr,5,4,yes,0
233,2024-04-05,2024-04-05 15:54:16,15,cash,No card,40.00,Cappuccino,Afternoon,Fri,Apr,5,4,yes,0
235,2024-04-05,2024-04-05 16:17:44,16,cash,No card,40.00,Cocoa,Afternoon,Fri,Apr,5,4,yes,0
89,2024-03-12,2024-03-12 10:15:00,10,cash,No card,40.00,Latte,Morning,Tue,Mar,2,3,yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,2024-08-14,2024-08-14 11:39:08,11,card,ANON-0000-0000-0095,18.12,Espresso,Morning,Wed,Aug,3,8,No,1
1193,2024-08-07,2024-08-07 13:11:16,13,card,ANON-0000-0000-0469,18.12,Espresso,Afternoon,Wed,Aug,3,8,No,1
1200,2024-08-08,2024-08-08 08:46:36,8,card,ANON-0000-0000-0141,18.12,Espresso,Morning,Thu,Aug,4,8,No,1
1581,2024-09-17,2024-09-17 12:38:34,12,card,ANON-0000-0000-0628,18.12,Espresso,Afternoon,Tue,Sep,2,9,No,1
1027,2024-07-24,2024-07-24 14:45:50,14,card,ANON-0000-0000-0012,18.12,Espresso,Afternoon,Wed,Jul,3,7,No,1

In [ ]:
# GroupBy (total sales per coffee)

grouped = data_csv.groupby("coffee_name")["money"].sum()

print(grouped)

coffee_name
Americano              15062.26
Americano with Milk    25269.12
Cappuccino             18034.14
Cocoa                   8678.16
Cortado                 7534.86
Espresso                2814.28
Hot Chocolate          10172.46
Latte                  27866.30
Name: money, dtype: float64