In [1]:
import numpy as np
import pandas as pd

In [2]:
data_excel = pd.read_excel("data/Coffe_sales.xlsx")
data_csv = pd.read_csv("data/coffee_sales.csv")

In [3]:
data_excel

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,2024-03-01,2024-03-01 10:15:50.520,10,card,ANON-0000-0000-0001,38.70,Latte,Morning,Fri,Mar,5,3
1,2024-03-01,2024-03-01 12:19:22.539,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,2024-03-01,2024-03-01 12:20:18.089,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,2024-03-01,2024-03-01 13:46:33.006,13,card,ANON-0000-0000-0003,28.90,Americano,Afternoon,Fri,Mar,5,3
4,2024-03-01,2024-03-01 13:48:14.626,13,card,ANON-0000-0000-0004,38.70,Latte,Afternoon,Fri,Mar,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,10,card,ANON-0000-0000-1158,35.76,Cappuccino,Morning,Sun,Mar,7,3
3632,2025-03-23,2025-03-23 14:43:37.362,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,2025-03-23,2025-03-23 14:44:16.864,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3634,2025-03-23,2025-03-23 15:47:28.723,15,card,ANON-0000-0000-1316,25.96,Americano,Afternoon,Sun,Mar,7,3
3635,2025-03-23,2025-03-23 18:11:38.635,18,card,ANON-0000-0000-1275,35.76,Latte,Night,Sun,Mar,7,3

In [4]:
data_csv

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,01/03/2024,01/03/2024 10:15:51,10,card,ANON-0000-0000-0001,R38.70,Latte,Morning,Fri,Mar,5,3
1,01/03/2024,01/03/2024 12:19:23,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,01/03/2024,01/03/2024 12:20:18,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,01/03/2024,01/03/2024 13:46:33,13,card,ANON-0000-0000-0003,R28.90,Americano,Afternoon,Fri,Mar,5,3
4,01/03/2024,01/03/2024 13:48:15,13,card,ANON-0000-0000-0004,R38.70,Latte,Afternoon,Fri,Mar,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3631,23/03/2025,23/03/2025 10:34:55,10,card,ANON-0000-0000-1158,R35.76,Cappuccino,Morning,Sun,Mar,7,3
3632,23/03/2025,23/03/2025 14:43:37,14,card,ANON-0000-0000-1315,R35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,23/03/2025,23/03/2025 14:44:17,14,card,ANON-0000-0000-1315,R35.76,Cocoa,Afternoon,Sun,Mar,7,3
3634,23/03/2025,23/03/2025 15:47:29,15,card,ANON-0000-0000-1316,R25.96,Americano,Afternoon,Sun,Mar,7,3
3635,23/03/2025,23/03/2025 18:11:39,18,card,ANON-0000-0000-1275,R35.76,Latte,Night,Sun,Mar,7,3

In [5]:
print(type(data_excel))

<class 'pandas.DataFrame'>

In [6]:
print(type(data_csv))

<class 'pandas.DataFrame'>

In [7]:
data_excel.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   datetime64[us]
 1   datetime     3636 non-null   datetime64[us]
 2   hour_of_day  3636 non-null   int64
 3   cash_type    3636 non-null   str
 4   card         3547 non-null   str
 5   money        3636 non-null   float64
 6   coffee_name  3636 non-null   str
 7   Time_of_Day  3636 non-null   str
 8   Weekday      3636 non-null   str
 9   Month_name   3636 non-null   str
 10  Weekdaysort  3636 non-null   int64
 11  Monthsort    3636 non-null   int64
dtypes: datetime64[us](2), float64(1), int64(3), str(6)
memory usage: 341.0 KB

In [8]:
data_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   str
 1   datetime     3636 non-null   str
 2   hour_of_day  3636 non-null   int64
 3   cash_type    3636 non-null   str
 4   card         3547 non-null   str
 5   money        3636 non-null   str
 6   coffee_name  3636 non-null   str
 7   Time_of_Day  3636 non-null   str
 8   Weekday      3636 non-null   str
 9   Month_name   3636 non-null   str
 10  Weekdaysort  3636 non-null   int64
 11  Monthsort    3636 non-null   int64
dtypes: int64(3), str(9)
memory usage: 341.0 KB

In [9]:
data_excel.shape

(3636, 12)

In [10]:
data_csv.shape

(3636, 12)

In [11]:
data_excel.head()

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,2024-03-01,2024-03-01 10:15:50.520,10,card,ANON-0000-0000-0001,38.7,Latte,Morning,Fri,Mar,5,3
1,2024-03-01,2024-03-01 12:19:22.539,12,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,2024-03-01,2024-03-01 12:20:18.089,12,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,2024-03-01,2024-03-01 13:46:33.006,13,card,ANON-0000-0000-0003,28.9,Americano,Afternoon,Fri,Mar,5,3
4,2024-03-01,2024-03-01 13:48:14.626,13,card,ANON-0000-0000-0004,38.7,Latte,Afternoon,Fri,Mar,5,3

In [12]:
data_csv.head()

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,01/03/2024,01/03/2024 10:15:51,10,card,ANON-0000-0000-0001,R38.70,Latte,Morning,Fri,Mar,5,3
1,01/03/2024,01/03/2024 12:19:23,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,01/03/2024,01/03/2024 12:20:18,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,01/03/2024,01/03/2024 13:46:33,13,card,ANON-0000-0000-0003,R28.90,Americano,Afternoon,Fri,Mar,5,3
4,01/03/2024,01/03/2024 13:48:15,13,card,ANON-0000-0000-0004,R38.70,Latte,Afternoon,Fri,Mar,5,3

In [13]:
data_excel.dtypes

date           datetime64[us]
datetime       datetime64[us]
hour_of_day             int64
cash_type                 str
card                      str
money                 float64
coffee_name               str
Time_of_Day               str
Weekday                   str
Month_name                str
Weekdaysort             int64
Monthsort               int64
dtype: object

In [14]:
data_excel.columns

Index(['date', 'datetime', 'hour_of_day', 'cash_type', 'card', 'money',
       'coffee_name', 'Time_of_Day', 'Weekday', 'Month_name', 'Weekdaysort',
       'Monthsort'],
      dtype='str')

In [15]:
data_excel.describe()

,date,datetime,hour_of_day,money,Weekdaysort,Monthsort
count,3636,3636,3636.000000,3636.000000,3636.000000,3636.000000
mean,2024-09-30 11:56:02.376237,2024-10-01 02:35:30.535053,14.166942,31.746859,3.847910,6.394664
min,2024-03-01 00:00:00,2024-03-01 10:15:50.520000,6.000000,18.120000,1.000000,1.000000
25%,2024-07-03 00:00:00,2024-07-03 16:54:06.084750,10.000000,27.920000,2.000000,3.000000
50%,2024-10-06 12:00:00,2024-10-07 02:55:12.649500,14.000000,32.820000,4.000000,6.000000
75%,2025-01-08 00:00:00,2025-01-08 07:55:20.299750,18.000000,35.760000,6.000000,10.000000
max,2025-03-23 00:00:00,2025-03-23 18:11:38.635000,22.000000,40.000000,7.000000,12.000000
std,NaN,NaN,4.227755,4.919926,1.975983,3.480686

In [16]:
data_excel.isna().sum()

date            0
datetime        0
hour_of_day     0
cash_type       0
card           89
money           0
coffee_name     0
Time_of_Day     0
Weekday         0
Month_name      0
Weekdaysort     0
Monthsort       0
dtype: int64

In [17]:
data_excel["money"].describe()

count    3636.000000
mean       31.746859
std         4.919926
min        18.120000
25%        27.920000
50%        32.820000
75%        35.760000
max        40.000000
Name: money, dtype: float64

In [18]:
data_excel["money"].quantile(0.5)

np.float64(32.82)

In [19]:
data_excel.index

RangeIndex(start=0, stop=3636, step=1)

In [20]:
data_excel.sample(5)

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
2320,2024-11-15,2024-11-15 12:14:18.551,12,card,ANON-0000-0000-0904,35.76,Cocoa,Afternoon,Fri,Nov,5,11
3432,2025-03-09,2025-03-09 15:53:40.394,15,card,ANON-0000-0000-1270,35.76,Cocoa,Afternoon,Sun,Mar,7,3
663,2024-05-31,2024-05-31 20:06:39.166,20,card,ANON-0000-0000-0180,37.72,Cappuccino,Night,Fri,May,5,5
932,2024-07-07,2024-07-07 09:14:29.225,9,card,ANON-0000-0000-0353,27.92,Americano with Milk,Morning,Sun,Jul,7,7
2433,2024-11-30,2024-11-30 22:03:48.484,22,card,ANON-0000-0000-0957,30.86,Americano with Milk,Night,Sat,Nov,6,11

## Creating

### 1. From a list

In [21]:
my_list = [1, 2, 3, 4, 5]
s = pd.Series(my_list)
print("Type of my_list variable is", type(my_list))
print("Type of variable 's' is", type(s))
print(s)

Type of my_list variable is <class 'list'>
Type of variable 's' is <class 'pandas.Series'>
0    1
1    2
2    3
3    4
4    5
dtype: int64

### 2. With custom index

In [22]:
fruits = pd.Series (["Apple", "Banana", "Mango", "Orange"], index=[350, 240, 200, 250])

fruits

350     Apple
240    Banana
200     Mango
250    Orange
dtype: str

In [23]:
fruits.values

<StringArray>
['Apple', 'Banana', 'Mango', 'Orange']
Length: 4, dtype: str

In [24]:
fruits.index

Index([350, 240, 200, 250], dtype='int64')

### Using Dictionary

In [25]:
veggies = pd.Series({
    "Potato": 60,
    "Tomato": 80,
    "Onion": 70,
    "Carrot": 90})

print(veggies)

Potato    60
Tomato    80
Onion     70
Carrot    90
dtype: int64

In [26]:
veggies["Potato"]

np.int64(60)

In [27]:
veggies["Tomato":"Carrot"]

Tomato    80
Onion     70
Carrot    90
dtype: int64

### 4. From a Scaler Value

In [28]:
s1 = pd.Series(10, index= range(10))
s1

0    10
1    10
2    10
3    10
4    10
5    10
6    10
7    10
8    10
9    10
dtype: int64

## DataFrame

**1. From Dictionary of Lists / Numpy Arrays**

In [29]:
# From Dictionary of Lists / NumPy Arrays
data = {
    'Name': pd.Series(['Alice', 'Bob', 'Charlie', 'David'], index=["A", "B", "C", "D"]),
    'Age': np.array([25, 30, 35, 28]),
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

In [30]:
df_dict = pd.DataFrame(data)
df_dict

      Name  Age      City
A    Alice   25  New York
B      Bob   30    London
C  Charlie   35     Paris
D    David   28     Tokyo

In [31]:
df_indexed = pd.DataFrame(data, index=['A', 'B', 'C', 'D'])
df_indexed

      Name  Age      City
A    Alice   25  New York
B      Bob   30    London
C  Charlie   35     Paris
D    David   28     Tokyo

### 3 From Numpy Array

In [32]:
# Creating a DataFrame from a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_numpy = pd.DataFrame(arr)
df_numpy

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [33]:
df_numpy = pd.DataFrame(arr, columns=["A", "B", "C"], index=["a", "b", "c"])
df_numpy

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [34]:
# Transpose

df_numpy.T

   a  b  c
A  1  4  7
B  2  5  8
C  3  6  9

## Data Selection and Indexing

**Selecting columns**

In [35]:
data_excel["coffee_name"]

0               Latte
1       Hot Chocolate
2       Hot Chocolate
3           Americano
4               Latte
            ...
3631       Cappuccino
3632            Cocoa
3633            Cocoa
3634        Americano
3635            Latte
Name: coffee_name, Length: 3636, dtype: str

In [36]:
# Selecting multiple columns
# multiple column cha hiyo vanay double big bracket dinna paryoo

data_excel[["coffee_name", "money", "cash_type"]]

        coffee_name  money cash_type
0             Latte  38.70      card
1     Hot Chocolate  38.70      card
2     Hot Chocolate  38.70      card
3         Americano  28.90      card
4             Latte  38.70      card
...             ...    ...       ...
3631     Cappuccino  35.76      card
3632          Cocoa  35.76      card
3633          Cocoa  35.76      card
3634      Americano  25.96      card
3635          Latte  35.76      card

[3636 rows x 3 columns]

In [37]:
#  Dot notation

data_excel.coffee_name

0               Latte
1       Hot Chocolate
2       Hot Chocolate
3           Americano
4               Latte
            ...
3631       Cappuccino
3632            Cocoa
3633            Cocoa
3634        Americano
3635            Latte
Name: coffee_name, Length: 3636, dtype: str

### .loc[]

In [38]:
data_excel.loc[0]

date                  2024-03-01 00:00:00
datetime       2024-03-01 10:15:50.520000
hour_of_day                            10
cash_type                            card
card                  ANON-0000-0000-0001
money                                38.7
coffee_name                         Latte
Time_of_Day                       Morning
Weekday                               Fri
Month_name                            Mar
Weekdaysort                             5
Monthsort                               3
Name: 0, dtype: object

In [39]:
data_excel.loc[0, "coffee_name"]

'Latte'

In [40]:
data_excel.loc[5:10]

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
5,2024-03-01,2024-03-01 15:39:47.726,15,card,ANON-0000-0000-0005,33.8,Americano with Milk,Afternoon,Fri,Mar,5,3
6,2024-03-01,2024-03-01 16:19:02.756,16,card,ANON-0000-0000-0006,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
7,2024-03-01,2024-03-01 18:39:03.580,18,card,ANON-0000-0000-0007,33.8,Americano with Milk,Night,Fri,Mar,5,3
8,2024-03-01,2024-03-01 19:22:01.762,19,card,ANON-0000-0000-0008,38.7,Cocoa,Night,Fri,Mar,5,3
9,2024-03-01,2024-03-01 19:23:15.887,19,card,ANON-0000-0000-0008,33.8,Americano with Milk,Night,Fri,Mar,5,3
10,2024-03-01,2024-03-01 19:29:17.391,19,card,ANON-0000-0000-0009,33.8,Americano with Milk,Night,Fri,Mar,5,3

In [41]:
data_excel.loc[5:10, "cash_type":"coffee_name"]

   cash_type                 card  money          coffee_name
5       card  ANON-0000-0000-0005   33.8  Americano with Milk
6       card  ANON-0000-0000-0006   38.7        Hot Chocolate
7       card  ANON-0000-0000-0007   33.8  Americano with Milk
8       card  ANON-0000-0000-0008   38.7                Cocoa
9       card  ANON-0000-0000-0008   33.8  Americano with Milk
10      card  ANON-0000-0000-0009   33.8  Americano with Milk

In [42]:
data_excel.loc[3631:, ["Month_name", "Weekdaysort", "Monthsort"]]

     Month_name  Weekdaysort  Monthsort
3631        Mar            7          3
3632        Mar            7          3
3633        Mar            7          3
3634        Mar            7          3
3635        Mar            7          3

In [43]:
# Last 5 rows and last 5 rows
data_excel.loc[3631:, "Month_name":]

     Month_name  Weekdaysort  Monthsort
3631        Mar            7          3
3632        Mar            7          3
3633        Mar            7          3
3634        Mar            7          3
3635        Mar            7          3

In [44]:
data_excel.tail()

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
3631,2025-03-23,2025-03-23 10:34:54.894,10,card,ANON-0000-0000-1158,35.76,Cappuccino,Morning,Sun,Mar,7,3
3632,2025-03-23,2025-03-23 14:43:37.362,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,2025-03-23,2025-03-23 14:44:16.864,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3634,2025-03-23,2025-03-23 15:47:28.723,15,card,ANON-0000-0000-1316,25.96,Americano,Afternoon,Sun,Mar,7,3
3635,2025-03-23,2025-03-23 18:11:38.635,18,card,ANON-0000-0000-1275,35.76,Latte,Night,Sun,Mar,7,3

In [45]:
data_excel.loc[:, ["Month_name", "Weekdaysort", "Monthsort"]].tail(5)

     Month_name  Weekdaysort  Monthsort
3631        Mar            7          3
3632        Mar            7          3
3633        Mar            7          3
3634        Mar            7          3
3635        Mar            7          3

In [46]:
data_excel.loc[:, ["coffee_name", "money", "cash_type"]]

        coffee_name  money cash_type
0             Latte  38.70      card
1     Hot Chocolate  38.70      card
2     Hot Chocolate  38.70      card
3         Americano  28.90      card
4             Latte  38.70      card
...             ...    ...       ...
3631     Cappuccino  35.76      card
3632          Cocoa  35.76      card
3633          Cocoa  35.76      card
3634      Americano  25.96      card
3635          Latte  35.76      card

[3636 rows x 3 columns]

In [47]:
data_excel.loc[:, ["coffee_name", "money", "cash_type"]].tail(5)

     coffee_name  money cash_type
3631  Cappuccino  35.76      card
3632       Cocoa  35.76      card
3633       Cocoa  35.76      card
3634   Americano  25.96      card
3635       Latte  35.76      card

In [48]:
data_excel.iloc[5:10, 3:7]

  cash_type                 card  money          coffee_name
5      card  ANON-0000-0000-0005   33.8  Americano with Milk
6      card  ANON-0000-0000-0006   38.7        Hot Chocolate
7      card  ANON-0000-0000-0007   33.8  Americano with Milk
8      card  ANON-0000-0000-0008   38.7                Cocoa
9      card  ANON-0000-0000-0008   33.8  Americano with Milk

In [49]:
data_excel.iloc[[6, 2, 3635, 5], [6, 5]]

              coffee_name  money
6           Hot Chocolate  38.70
2           Hot Chocolate  38.70
3635                Latte  35.76
5     Americano with Milk  33.80

In [50]:
data_excel.iloc[[-5, -4, -3, -2, -1], [-3, -2, -1]]

     Month_name  Weekdaysort  Monthsort
3631        Mar            7          3
3632        Mar            7          3
3633        Mar            7          3
3634        Mar            7          3
3635        Mar            7          3

In [51]:
data_excel.iloc[-5]

date                  2025-03-23 00:00:00
datetime       2025-03-23 10:34:54.894000
hour_of_day                            10
cash_type                            card
card                  ANON-0000-0000-1158
money                               35.76
coffee_name                    Cappuccino
Time_of_Day                       Morning
Weekday                               Sun
Month_name                            Mar
Weekdaysort                             7
Monthsort                               3
Name: 3631, dtype: object

In [52]:
data_excel.iloc[-5:, -3]

3631    Mar
3632    Mar
3633    Mar
3634    Mar
3635    Mar
Name: Month_name, dtype: str

In [53]:
# Last 5 rows and last 3 columns
data_excel.iloc[-5, -3]

'Mar'

In [54]:
data_excel.iloc[-5:, -3:]

     Month_name  Weekdaysort  Monthsort
3631        Mar            7          3
3632        Mar            7          3
3633        Mar            7          3
3634        Mar            7          3
3635        Mar            7          3

In [55]:
data_excel.loc[10, "coffee_name"]

'Americano with Milk'

# Boolean indexing

In [56]:
data_excel["coffee_name"] == "Americano"

0       False
1       False
2       False
3        True
4       False
        ...
3631    False
3632    False
3633    False
3634     True
3635    False
Name: coffee_name, Length: 3636, dtype: bool

In [57]:
mask = data_excel["coffee_name"] == "Americano"

data_excel[mask]

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
3,2024-03-01,2024-03-01 13:46:33.006,13,card,ANON-0000-0000-0003,28.90,Americano,Afternoon,Fri,Mar,5,3
11,2024-03-02,2024-03-02 10:22:06.957,10,card,ANON-0000-0000-0010,28.90,Americano,Morning,Sat,Mar,6,3
15,2024-03-02,2024-03-02 14:38:35.535,14,card,ANON-0000-0000-0013,28.90,Americano,Afternoon,Sat,Mar,6,3
17,2024-03-02,2024-03-02 17:34:54.969,17,card,ANON-0000-0000-0004,28.90,Americano,Night,Sat,Mar,6,3
21,2024-03-03,2024-03-03 12:26:56.098,12,card,ANON-0000-0000-0012,28.90,Americano,Afternoon,Sun,Mar,7,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3610,2025-03-21,2025-03-21 15:24:42.515,15,card,ANON-0000-0000-1170,25.96,Americano,Afternoon,Fri,Mar,5,3
3617,2025-03-21,2025-03-21 18:59:24.271,18,card,ANON-0000-0000-1170,25.96,Americano,Night,Fri,Mar,5,3
3623,2025-03-22,2025-03-22 12:25:59.676,12,card,ANON-0000-0000-1306,25.96,Americano,Afternoon,Sat,Mar,6,3
3624,2025-03-22,2025-03-22 13:06:21.590,13,card,ANON-0000-0000-1309,25.96,Americano,Afternoon,Sat,Mar,6,3
3634,2025-03-23,2025-03-23 15:47:28.723,15,card,ANON-0000-0000-1316,25.96,Americano,Afternoon,Sun,Mar,7,3

In [58]:
data_excel[data_excel["money"] > 30]

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,2024-03-01,2024-03-01 10:15:50.520,10,card,ANON-0000-0000-0001,38.70,Latte,Morning,Fri,Mar,5,3
1,2024-03-01,2024-03-01 12:19:22.539,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,2024-03-01,2024-03-01 12:20:18.089,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
4,2024-03-01,2024-03-01 13:48:14.626,13,card,ANON-0000-0000-0004,38.70,Latte,Afternoon,Fri,Mar,5,3
5,2024-03-01,2024-03-01 15:39:47.726,15,card,ANON-0000-0000-0005,33.80,Americano with Milk,Afternoon,Fri,Mar,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3630,2025-03-23,2025-03-23 10:07:11.278,10,card,ANON-0000-0000-1196,35.76,Latte,Morning,Sun,Mar,7,3
3631,2025-03-23,2025-03-23 10:34:54.894,10,card,ANON-0000-0000-1158,35.76,Cappuccino,Morning,Sun,Mar,7,3
3632,2025-03-23,2025-03-23 14:43:37.362,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,2025-03-23,2025-03-23 14:44:16.864,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3635,2025-03-23,2025-03-23 18:11:38.635,18,card,ANON-0000-0000-1275,35.76,Latte,Night,Sun,Mar,7,3

In [59]:
data_excel[data_excel["money"] > 30]["coffee_name"]

0                     Latte
1             Hot Chocolate
2             Hot Chocolate
4                     Latte
5       Americano with Milk
               ...
3630                  Latte
3631             Cappuccino
3632                  Cocoa
3633                  Cocoa
3635                  Latte
Name: coffee_name, Length: 2410, dtype: str

In [60]:
data_excel.loc[data_excel["money"] > 30, ["coffee_name", "money"]]

              coffee_name  money
0                   Latte  38.70
1           Hot Chocolate  38.70
2           Hot Chocolate  38.70
4                   Latte  38.70
5     Americano with Milk  33.80
...                   ...    ...
3630                Latte  35.76
3631           Cappuccino  35.76
3632                Cocoa  35.76
3633                Cocoa  35.76
3635                Latte  35.76

[2410 rows x 2 columns]

In [61]:
data_excel.loc[data_excel["money"] > 30] ["coffee_name"].nunique()

5

In [62]:
data_excel.loc[data_excel["date"] == "28/04/2024", "coffee_name"]

381         Latte
382    Cappuccino
383     Americano
384     Americano
385         Latte
Name: coffee_name, dtype: str

In [63]:
data_excel.loc[data_excel["date"] == "28/04/2024", "coffee_name"]

381         Latte
382    Cappuccino
383     Americano
384     Americano
385         Latte
Name: coffee_name, dtype: str

In [64]:
data_excel.loc[data_excel["date"] == "28/04/2024", "coffee_name"]

381         Latte
382    Cappuccino
383     Americano
384     Americano
385         Latte
Name: coffee_name, dtype: str

In [65]:
data_excel[data_excel["date"] == '2024-04-28'].count()

date           5
datetime       5
hour_of_day    5
cash_type      5
card           5
money          5
coffee_name    5
Time_of_Day    5
Weekday        5
Month_name     5
Weekdaysort    5
Monthsort      5
dtype: int64

In [66]:
data_excel[data_excel["date"] == '2024-04-28']["Weekday"]

381    Sun
382    Sun
383    Sun
384    Sun
385    Sun
Name: Weekday, dtype: str

In [67]:
data_excel[data_excel["date"] == '2024-04-28']["Weekday"]

381    Sun
382    Sun
383    Sun
384    Sun
385    Sun
Name: Weekday, dtype: str

In [68]:
data_excel[data_excel["date"] == '2024-04-28']["Weekday"].unique()

<StringArray>
['Sun']
Length: 1, dtype: str

In [69]:
data_excel.loc[data_excel["date"] == "28/04/2024", ["coffee_name", "Weekday"]]

    coffee_name Weekday
381       Latte     Sun
382  Cappuccino     Sun
383   Americano     Sun
384   Americano     Sun
385       Latte     Sun

In [70]:
# group by
data_excel.groupby("coffee_name")["coffee_name"].count().sort_values(ascending=False)

coffee_name
Americano with Milk    824
Latte                  782
Americano              578
Cappuccino             501
Cortado                292
Hot Chocolate          282
Cocoa                  243
Espresso               134
Name: coffee_name, dtype: int64

In [71]:
data_excel.groupby("coffee_name")["money"].sum().sort_values(ascending=False)

coffee_name
Latte                  27866.30
Americano with Milk    25269.12
Cappuccino             18034.14
Americano              15062.26
Hot Chocolate          10172.46
Cocoa                   8678.16
Cortado                 7534.86
Espresso                2814.28
Name: money, dtype: float64

In [72]:
data_excel.groupby("coffee_name")["money"].agg(["sum", "min", "max", "count"])

                          sum    min   max  count
coffee_name
Americano            15062.26  23.02  30.0    578
Americano with Milk  25269.12  27.92  35.0    824
Cappuccino           18034.14  32.82  40.0    501
Cocoa                 8678.16  32.82  40.0    243
Cortado               7534.86  23.02  30.0    292
Espresso              2814.28  18.12  25.0    134
Hot Chocolate        10172.46  32.82  40.0    282
Latte                27866.30  32.82  40.0    782

In [73]:
# dictionary (key= value, aggregation)

data_excel.groupby("coffee_name").agg({"coffee_name": "count", "money": ["sum", "mean"], "date": "max"})

                    coffee_name     money                  date
                          count       sum       mean        max
coffee_name
Americano                   578  15062.26  26.059273 2025-03-23
Americano with Milk         824  25269.12  30.666408 2025-03-22
Cappuccino                  501  18034.14  35.996287 2025-03-23
Cocoa                       243   8678.16  35.712593 2025-03-23
Cortado                     292   7534.86  25.804315 2025-03-20
Espresso                    134   2814.28  21.002090 2025-03-22
Hot Chocolate               282  10172.46  36.072553 2025-03-22
Latte                       782  27866.30  35.634655 2025-03-23

In [74]:
aggregations = {
    "coffee_name": "count",
    "money": ["sum", "mean"],
    "date": "max"
}

data_excel.groupby("coffee_name").agg(aggregations)

                    coffee_name     money                  date
                          count       sum       mean        max
coffee_name
Americano                   578  15062.26  26.059273 2025-03-23
Americano with Milk         824  25269.12  30.666408 2025-03-22
Cappuccino                  501  18034.14  35.996287 2025-03-23
Cocoa                       243   8678.16  35.712593 2025-03-23
Cortado                     292   7534.86  25.804315 2025-03-20
Espresso                    134   2814.28  21.002090 2025-03-22
Hot Chocolate               282  10172.46  36.072553 2025-03-22
Latte                       782  27866.30  35.634655 2025-03-23

In [75]:
data_excel.head()

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,2024-03-01,2024-03-01 10:15:50.520,10,card,ANON-0000-0000-0001,38.7,Latte,Morning,Fri,Mar,5,3
1,2024-03-01,2024-03-01 12:19:22.539,12,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,2024-03-01,2024-03-01 12:20:18.089,12,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,2024-03-01,2024-03-01 13:46:33.006,13,card,ANON-0000-0000-0003,28.9,Americano,Afternoon,Fri,Mar,5,3
4,2024-03-01,2024-03-01 13:48:14.626,13,card,ANON-0000-0000-0004,38.7,Latte,Afternoon,Fri,Mar,5,3

In [76]:
data_excel.dtypes

date           datetime64[us]
datetime       datetime64[us]
hour_of_day             int64
cash_type                 str
card                      str
money                 float64
coffee_name               str
Time_of_Day               str
Weekday                   str
Month_name                str
Weekdaysort             int64
Monthsort               int64
dtype: object

In [77]:
data_excel["date"].dt.year

0       2024
1       2024
2       2024
3       2024
4       2024
        ...
3631    2025
3632    2025
3633    2025
3634    2025
3635    2025
Name: date, Length: 3636, dtype: int32

In [78]:
data_2024 = data_excel[data_excel["date"].dt.year == 2024]

result = data_2024.groupby(["coffee_name", "Time_of_Day"])["money"].sum()

print(result)

coffee_name          Time_of_Day
Americano            Afternoon      3661.02
                     Morning        3146.22
                     Night          1920.78
Americano with Milk  Afternoon      6106.94
                     Morning        7360.40
                     Night          5969.24
Cappuccino           Afternoon      4179.66
                     Morning        3270.60
                     Night          6221.16
Cocoa                Afternoon      1438.56
                     Morning        1490.46
                     Night          2173.14
Cortado              Afternoon      1964.52
                     Morning        3431.82
                     Night          1255.88
Espresso             Afternoon       986.44
                     Morning         670.00
                     Night           483.92
Hot Chocolate        Afternoon      1941.98
                     Morning        1212.24
                     Night          4515.04
Latte                Afternoon      6937.58
                     Morning        7616.46
                     Night          7876.74
Name: money, dtype: float64

**Find the best selling drink of 2024**

In [79]:
data_2024 = data_excel[data_excel["date"].dt.year == 2024]

best_selling = data_2024["coffee_name"].value_counts()

print(best_selling.head(1))

coffee_name
Americano with Milk    635
Name: count, dtype: int64

In [80]:
data_2024 = data_excel[data_excel["date"].dt.year == 2024]

best_selling = data_2024["coffee_name"].value_counts()

print(best_selling.index[0])

Americano with Milk

In [81]:
data_excel.groupby('coffee_name')['coffee_name'].count().sort_values(ascending=False).head(1)

coffee_name
Americano with Milk    824
Name: coffee_name, dtype: int64

In [82]:
data_excel[data_excel['date'].dt.year==2024].groupby('coffee_name')['card'].count().sort_values(ascending=False).head(1)

coffee_name
Americano with Milk    620
Name: card, dtype: int64

**At what time of day, is my average sales high?**

daily total sales by time of day?

avg sales by time of day.

In [95]:
daily_coffee_sales = data_excel.groupby(["date", "Time_of_Day"])["money"].sum().reset_index()
daily_coffee_sales

          date Time_of_Day   money
0   2024-03-01   Afternoon  217.50
1   2024-03-01     Morning   38.70
2   2024-03-01       Night  140.10
3   2024-03-02   Afternoon   62.70
4   2024-03-02     Morning  136.50
..         ...         ...     ...
970 2025-03-22     Morning  133.24
971 2025-03-22       Night   61.72
972 2025-03-23   Afternoon   97.48
973 2025-03-23     Morning   71.52
974 2025-03-23       Night   35.76

[975 rows x 3 columns]

In [112]:
daily_coffee_sales = data_excel.groupby(["date", "Time_of_Day"]).agg(total_sales=("money", "sum")).reset_index()
daily_coffee_sales.groupby("Time_of_Day").agg(avg_sales=("total_sales", "mean")).sort_values(by=["avg_sales"], ascending=False)

              avg_sales
Time_of_Day
Night        125.914000
Afternoon    120.055508
Morning      109.941765

In [84]:
daily_coffee_sales_df = data_excel.groupby(["date", "Time_of_Day"]).agg(total_sales=("money", "sum")).reset_index()
daily_coffee_sales_df.groupby("Time_of_Day").agg(avg_sales=("total_sales", "mean")).sort_values(by=["avg_sales"], ascending=False)

              avg_sales
Time_of_Day
Night        125.914000
Afternoon    120.055508
Morning      109.941765

In [85]:
data_excel.dtypes

date           datetime64[us]
datetime       datetime64[us]
hour_of_day             int64
cash_type                 str
card                      str
money                 float64
coffee_name               str
Time_of_Day               str
Weekday                   str
Month_name                str
Weekdaysort             int64
Monthsort               int64
dtype: object

**3. What is the revenue generated at last month of the year 2024?**

In [86]:
# generated at end of the month for the year 2024?
 
data_2024.groupby([ 'Monthsort'])['money'].sum().tail(1)

Monthsort
12    8237.74
Name: money, dtype: float64

In [87]:
december = data_excel[(data_excel["date"].dt.year == 2024) & (data_2024["date"].dt.month == 12)]["money"].sum()

print(december)

8237.74

**4. What is the sales trend at the last quarter of 2024?**

In [88]:
data_2024.groupby(['Monthsort'])['money'].sum().tail(3)

Monthsort
10    13891.16
11     8590.54
12     8237.74
Name: money, dtype: float64

**5. At what time of the day do people drink hot chocolate the most?**

In [89]:
hot_chocolate = data_excel[data_excel["coffee_name"] == "Hot Chocolate"]

In [90]:
mostly_drink = hot_chocolate.groupby("Time_of_Day")["money"].count().sort_values(ascending=False).head(1)
print(mostly_drink)

Time_of_Day
Night    150
Name: money, dtype: int64

In [91]:
hot_chocolate["Time_of_Day"].value_counts()

Time_of_Day
Night        150
Afternoon     82
Morning       50
Name: count, dtype: int64

**6. Find the latest transaction timestamp by cash type for all the drinks.**

In [92]:
data_excel.groupby(["cash_type", "coffee_name"])["datetime"].max()

cash_type  coffee_name
card       Americano             2025-03-23 15:47:28.723
           Americano with Milk   2025-03-22 19:16:52.727
           Cappuccino            2025-03-23 10:34:54.894
           Cocoa                 2025-03-23 14:44:16.864
           Cortado               2025-03-20 14:25:04.690
           Espresso              2025-03-22 15:57:58.183
           Hot Chocolate         2025-03-22 11:14:05.960
           Latte                 2025-03-23 18:11:38.635
cash       Americano             2024-05-25 12:40:23.587
           Americano with Milk   2024-06-03 21:43:37.471
           Cappuccino            2024-05-28 17:21:43.967
           Cocoa                 2024-06-01 20:54:59.267
           Cortado               2024-04-14 12:29:06.877
           Espresso              2024-05-19 09:28:49.723
           Hot Chocolate         2024-05-23 22:55:36.926
           Latte                 2024-05-31 09:23:58.791
Name: datetime, dtype: datetime64[us]

### Multiple filters