In [17]:
import numpy as np
import pandas as pd

In [18]:
data_excel = pd.read_excel("data/Coffe_sales.xlsx")
data_csv = pd.read_csv("data/coffee_sales.csv")

In [19]:
data_excel

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,2024-03-01,2024-03-01 10:15:50.520,10,card,ANON-0000-0000-0001,38.70,Latte,Morning,Fri,Mar,5,3
1,2024-03-01,2024-03-01 12:19:22.539,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,2024-03-01,2024-03-01 12:20:18.089,12,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,2024-03-01,2024-03-01 13:46:33.006,13,card,ANON-0000-0000-0003,28.90,Americano,Afternoon,Fri,Mar,5,3
4,2024-03-01,2024-03-01 13:48:14.626,13,card,ANON-0000-0000-0004,38.70,Latte,Afternoon,Fri,Mar,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,10,card,ANON-0000-0000-1158,35.76,Cappuccino,Morning,Sun,Mar,7,3
3632,2025-03-23,2025-03-23 14:43:37.362,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,2025-03-23,2025-03-23 14:44:16.864,14,card,ANON-0000-0000-1315,35.76,Cocoa,Afternoon,Sun,Mar,7,3
3634,2025-03-23,2025-03-23 15:47:28.723,15,card,ANON-0000-0000-1316,25.96,Americano,Afternoon,Sun,Mar,7,3
3635,2025-03-23,2025-03-23 18:11:38.635,18,card,ANON-0000-0000-1275,35.76,Latte,Night,Sun,Mar,7,3

In [20]:
data_csv

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,01/03/2024,01/03/2024 10:15:51,10,card,ANON-0000-0000-0001,R38.70,Latte,Morning,Fri,Mar,5,3
1,01/03/2024,01/03/2024 12:19:23,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,01/03/2024,01/03/2024 12:20:18,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,01/03/2024,01/03/2024 13:46:33,13,card,ANON-0000-0000-0003,R28.90,Americano,Afternoon,Fri,Mar,5,3
4,01/03/2024,01/03/2024 13:48:15,13,card,ANON-0000-0000-0004,R38.70,Latte,Afternoon,Fri,Mar,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3631,23/03/2025,23/03/2025 10:34:55,10,card,ANON-0000-0000-1158,R35.76,Cappuccino,Morning,Sun,Mar,7,3
3632,23/03/2025,23/03/2025 14:43:37,14,card,ANON-0000-0000-1315,R35.76,Cocoa,Afternoon,Sun,Mar,7,3
3633,23/03/2025,23/03/2025 14:44:17,14,card,ANON-0000-0000-1315,R35.76,Cocoa,Afternoon,Sun,Mar,7,3
3634,23/03/2025,23/03/2025 15:47:29,15,card,ANON-0000-0000-1316,R25.96,Americano,Afternoon,Sun,Mar,7,3
3635,23/03/2025,23/03/2025 18:11:39,18,card,ANON-0000-0000-1275,R35.76,Latte,Night,Sun,Mar,7,3

In [21]:
print(type(data_excel))

<class 'pandas.DataFrame'>

In [22]:
print(type(data_csv))

<class 'pandas.DataFrame'>

In [23]:
data_excel.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   datetime64[us]
 1   datetime     3636 non-null   datetime64[us]
 2   hour_of_day  3636 non-null   int64
 3   cash_type    3636 non-null   str
 4   card         3547 non-null   str
 5   money        3636 non-null   float64
 6   coffee_name  3636 non-null   str
 7   Time_of_Day  3636 non-null   str
 8   Weekday      3636 non-null   str
 9   Month_name   3636 non-null   str
 10  Weekdaysort  3636 non-null   int64
 11  Monthsort    3636 non-null   int64
dtypes: datetime64[us](2), float64(1), int64(3), str(6)
memory usage: 341.0 KB

In [26]:
data_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   str
 1   datetime     3636 non-null   str
 2   hour_of_day  3636 non-null   int64
 3   cash_type    3636 non-null   str
 4   card         3547 non-null   str
 5   money        3636 non-null   str
 6   coffee_name  3636 non-null   str
 7   Time_of_Day  3636 non-null   str
 8   Weekday      3636 non-null   str
 9   Month_name   3636 non-null   str
 10  Weekdaysort  3636 non-null   int64
 11  Monthsort    3636 non-null   int64
dtypes: int64(3), str(9)
memory usage: 341.0 KB

In [24]:
data_excel.shape

(3636, 12)

In [28]:
data_csv.shape

(3636, 12)

In [25]:
data_excel.head()

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,2024-03-01,2024-03-01 10:15:50.520,10,card,ANON-0000-0000-0001,38.7,Latte,Morning,Fri,Mar,5,3
1,2024-03-01,2024-03-01 12:19:22.539,12,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,2024-03-01,2024-03-01 12:20:18.089,12,card,ANON-0000-0000-0002,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,2024-03-01,2024-03-01 13:46:33.006,13,card,ANON-0000-0000-0003,28.9,Americano,Afternoon,Fri,Mar,5,3
4,2024-03-01,2024-03-01 13:48:14.626,13,card,ANON-0000-0000-0004,38.7,Latte,Afternoon,Fri,Mar,5,3

In [27]:
data_csv.head()

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,01/03/2024,01/03/2024 10:15:51,10,card,ANON-0000-0000-0001,R38.70,Latte,Morning,Fri,Mar,5,3
1,01/03/2024,01/03/2024 12:19:23,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,01/03/2024,01/03/2024 12:20:18,12,card,ANON-0000-0000-0002,R38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,01/03/2024,01/03/2024 13:46:33,13,card,ANON-0000-0000-0003,R28.90,Americano,Afternoon,Fri,Mar,5,3
4,01/03/2024,01/03/2024 13:48:15,13,card,ANON-0000-0000-0004,R38.70,Latte,Afternoon,Fri,Mar,5,3

In [29]:
data_excel.dtypes

date           datetime64[us]
datetime       datetime64[us]
hour_of_day             int64
cash_type                 str
card                      str
money                 float64
coffee_name               str
Time_of_Day               str
Weekday                   str
Month_name                str
Weekdaysort             int64
Monthsort               int64
dtype: object

In [31]:
data_excel.columns

Index(['date', 'datetime', 'hour_of_day', 'cash_type', 'card', 'money',
       'coffee_name', 'Time_of_Day', 'Weekday', 'Month_name', 'Weekdaysort',
       'Monthsort'],
      dtype='str')

In [32]:
data_excel.describe()

,date,datetime,hour_of_day,money,Weekdaysort,Monthsort
count,3636,3636,3636.000000,3636.000000,3636.000000,3636.000000
mean,2024-09-30 11:56:02.376237,2024-10-01 02:35:30.535053,14.166942,31.746859,3.847910,6.394664
min,2024-03-01 00:00:00,2024-03-01 10:15:50.520000,6.000000,18.120000,1.000000,1.000000
25%,2024-07-03 00:00:00,2024-07-03 16:54:06.084750,10.000000,27.920000,2.000000,3.000000
50%,2024-10-06 12:00:00,2024-10-07 02:55:12.649500,14.000000,32.820000,4.000000,6.000000
75%,2025-01-08 00:00:00,2025-01-08 07:55:20.299750,18.000000,35.760000,6.000000,10.000000
max,2025-03-23 00:00:00,2025-03-23 18:11:38.635000,22.000000,40.000000,7.000000,12.000000
std,NaN,NaN,4.227755,4.919926,1.975983,3.480686

In [33]:
data_excel.isna().sum()

date            0
datetime        0
hour_of_day     0
cash_type       0
card           89
money           0
coffee_name     0
Time_of_Day     0
Weekday         0
Month_name      0
Weekdaysort     0
Monthsort       0
dtype: int64

In [34]:
data_excel["money"].describe()

count    3636.000000
mean       31.746859
std         4.919926
min        18.120000
25%        27.920000
50%        32.820000
75%        35.760000
max        40.000000
Name: money, dtype: float64

In [37]:
data_excel["money"].quantile(0.5)

np.float64(32.82)

In [38]:
data_excel.index

RangeIndex(start=0, stop=3636, step=1)

In [39]:
data_excel.sample()

,date,datetime,hour_of_day,cash_type,card,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
3083,2025-02-13,2025-02-13 19:06:30.373,19,card,ANON-0000-0000-1209,35.76,Latte,Night,Thu,Feb,4,2